name: pedantic_jagi
version: 0.0.1
description: >-
  My own Dart Linter rules corresponding to the guidelines in Effective Dart, Pedantic + personal (the strictest you can get).
homepage: https://github.com/adrianjagielak/pedantic_jagi

environment:
  sdk: '>=2.1.1 <3.0.0'